### ISSUE TITLE
Doesn't Work With IDEA 14.0.2 + Scala Plugin 1.2.1

### ISSUE THREAD

**Issue by reid-spencer** [vmunier/scalajs-cross-project-intellij#1]
I get this warning during import of the sbt files:

```
3:10:19 PM SBT project import
           The following source roots are outside of the corresponding base directories:
/Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/js/../shared/src/main/scala
/Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/js/../shared/src/test/scala
/Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/jvm/../shared/src/main/scala
/Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/jvm/../shared/src/test/scala

These source roots cannot be included in the IDEA project model.
           Please consider using shared SBT projects instead of shared source roots. 
```

Furthermore, when I compile with IDEA then I get this error:

```
Error:scalac: 
     while compiling: /Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/shared/src/main/scala/SharedTags.scala
        during phase: jsinterop
     library version: version 2.10.4
    compiler version: version 2.10.4
  reconstructed args: -Xplugin:/Users/reidspencer/.ivy2/cache/org.scala-js/scalajs-compiler_2.10.4/jars/scalajs-compiler_2.10.4-0.6.0-M3.jar -nobootcp -javabootclasspath : -classpath /Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/javafx-doclet.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/reidspencer/Code/experiments/scalajs-cross-project-intellij/shared/target/scala-2.10/classes:/Users/reidspencer/.ivy2/cache/com.scalatags/scalatags_2.10/jars/scalatags_2.10-0.4.3-M3.jar:/Users/reidspencer/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.4.jar
  last tree to typer: TypeTree(class TypedTag)
              symbol: class TypedTag in object Text (flags: case)
   symbol definition: case class TypedTag[+Output <: <?>] extends TypedTag[scalatags.text.Builder,Output,String] with Frag with Product with Serializable
                 tpe: scalatags.Text.TypedTag[String]
       symbol owners: class TypedTag -> object Text -> package scalatags
      context owners: method body -> object SharedTags -> package <empty>
== Enclosing template or block ==
DefDef( // def body: scalatags.Text.TypedTag[String] in object SharedTags
  <method>
  "body"
  []
  Nil
  <tpt> // tree.tpe=scalatags.Text.TypedTag[String]
  Apply(
    "h1"
    "Hello World from SharedTags!"
  )
)
== Expanded type of tree ==
TypeRef(
  pre = SingleType(
    pre = SingleType(
      pre = ThisType(package <root>)
      package scalatags
    )
    object Text
  )
  TypeSymbol(
    case class TypedTag[+Output <: String] extends TypedTag[scalatags.text.Builder,Output,String] with Frag with Product with Serializable

  )
  args = List(
    AliasTypeRef(
      pre = SingleType(pre = ThisType(package scala), object Predef)
      Alias(type String = String)
      normalize = TypeRef(
        TypeSymbol(
          final class String extends Serializable with Comparable[String] with CharSequence

        )
      )
    )
  )
)
uncaught exception during compilation: scala.reflect.internal.MissingRequirementError
```

followed by this error:

```
Error:scalac: Error: object scala.scalajs.js.Any in compiler mirror not found.
scala.reflect.internal.MissingRequirementError: object scala.scalajs.js.Any in compiler mirror not found.
    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
    at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
    at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
    at org.scalajs.core.compiler.JSDefinitions$JSDefinitionsClass.JSAnyClass$lzycompute(JSDefinitions.scala:31)
    at org.scalajs.core.compiler.JSDefinitions$JSDefinitionsClass.JSAnyClass(JSDefinitions.scala:31)
    at org.scalajs.core.compiler.JSDefinitions$JSDefinitionsClass.JSAnyModule$lzycompute(JSDefinitions.scala:69)
    at org.scalajs.core.compiler.JSDefinitions$JSDefinitionsClass.JSAnyModule(JSDefinitions.scala:69)
    at org.scalajs.core.compiler.JSDefinitions$JSDefinitionsClass.JSAny_fromFunction(JSDefinitions.scala:70)
    at org.scalajs.core.compiler.JSPrimitives$$anonfun$initWithPrimitives$1.apply$mcVI$sp(JSPrimitives.scala:77)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
    at org.scalajs.core.compiler.JSPrimitives.initWithPrimitives(JSPrimitives.scala:76)
    at org.scalajs.core.compiler.JSPrimitives.initPrepJSPrimitives(JSPrimitives.scala:62)
    at org.scalajs.core.compiler.PrepJSInterop$JSInteropPhase.run(PrepJSInterop.scala:49)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:126)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:102)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:48)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:29)
    at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
    at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:62)
    at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:20)
    at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

This is very similar to [what I reported in the Scala.js google group](https://groups.google.com/forum/#!topic/scala-js/yhFdymqCN0s)

**Comment by ozeebee** [comment]
My 2 bits here: I've had a hard time configuring a cross-build project that compiles in IntelliJ.
I'm using the latest IntelliJ (14.1.5) with up-to-date versions of the Scala and SBT plugins.
First I must say I **do not** use the `sbt-idea` plugin because it's no longer maintained. 

For 'standard' scala projects, what I usually do is create the project structure (folders + build.sbt) outside IntelliJ (using `g8 ozeebee/simple-scala-sbt.g8` for instance). I then create an Intellij Scala/SBT project on top of the existing folder. 
This workflow works quite well, even when changing the `build.sbt` file (no need to delete and re-generate the idea project files as it is the case for `sbt-idea`).

Now, for Scala.js cross-build projects the workflow described above doesn't work...
I tried this project's `build.sbt` file proposal without success. The shared project generated classes are simply not available in the JS ad JVM projects.
So, I simply added the 'shared' project as module dependency to the JS and JVM modules.
So far it looks good and compiles in Intellij as well as in SBT shell.

Hope this can help others trying to do the same.
And thanks for the `build.sbt` file ! 
cheers,
Ozb

**Comment by dadarom** [comment]
```
rm -r .idea .idea_modules
In IntelliJ, use `File/Open...`
``` 
+1
